CREATE DATABASE rcs_member;
USE rcs_member;
CREATE TABLE member (id INT PRIMARY KEY AUTO_INCREMENT,code INT,pass VARCHAR(32),user VARCHAR(32));
CREATE TABLE room_in (id INT PRIMARY KEY AUTO_INCREMENT, code INT,user VARCHAR(32));
